exclude: '^docs/|/migrations/|devcontainer.json'
default_stages: [commit]

default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.4
    hooks:
      - id: prettier
        args: ['--tab-width', '2', '--single-quote']
        exclude: 'learn_wagtail/templates/'

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.11.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.0
    hooks:
      - id: isort

  #- repo: https://github.com/PyCQA/flake8
  #  rev: 6.1.0
  #  hooks:
  #   - id: flake8
  #     args: ['--ignore=F401']
  #     exclude: 'load-xml-to-wagtail.py'

  #- repo: https://github.com/Riverside-Healthcare/djLint
  #  rev: v1.34.0
  #  hooks:
  #   - id: djlint-reformat-django
  #   - id: djlint-django
  #     args: ['--ignore=H031,H030,H005,T003,T002'] # avoid inline styles
