# Generated by Django 4.0.4 on 2023-12-20 07:00

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpage',
            name='jobcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='jobtitle',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='responsible_crew',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='subsystem',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='vessel_comment',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
